# Portfolio Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content Configuration Version
version: 2

# Personal Info
name: Yudhir Hiren Gala
title: Software Engineer
email: ygala@ucsd.edu
website: www.github.com/yg2334/

# Theme Settings
darkmode: false

# Social Links
github_username: yg2334
linkedin_username: yudhir-gala

# Profile Section
about_profile_image: images/pg3.jpg
about_content: | 
  Hi, I’m Yudhir, a Master’s student in Computer Science at the University of California, San Diego. As an aspiring software engineer, I have developed robust applications and web solutions during internships, gaining teamwork and leadership experience along the way. 

  My core interests are in backend development and machine learning, and I am currently exploring microservice architecture and scalable ML system design.

  Key Skills: <mark>MERN</mark>, <mark>Backend Development</mark>, and <mark>Pizza Enthusiast</mark>

      
content:
  # Education Section
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of California, San Diego
        sub_title: Master of Science in Computer Science
        caption: 2023 - 2025
        description: |
          - Selected Coursework:
            - Fall 2024: Statistical Natural Language Processing, Research (WIFIRE Lab, SDSC)
            - Spring 2024: Graduate Networked Systems, Parallel Computation 
            - Winter 2024: Algorithm Design & Analysis, Data Systems for ML, Unsupervised Learning
            - Fall 2023: Probabilistic Reasoning & Learning, Computer Vision 1 , Recommender System & Web Mining (Professor Julian McAuley)
            

      - layout: left
        title: University of Mumbai
        sub_title: Bachelor of Technology in Computer Engineering
        caption: 2019 - 2023
        description: |
          - Relevant Coursework: Algorithms & Data Structures, Operating System , Database Management Systems, Networks, Cryptography, Big Data Analytics, Machine Learning
  
  # Technical Skills
  - title: Technical Skills
    layout: text
    content: |
      - **Languages**: C, C++, Python, JavaScript, Java  
      - **Tools**: GitHub, ELK Stack, d3.js, Pandas, PyTorch, React.js, Docker  
      - **Databases**: MySQL, MongoDB, Elasticsearch  
      - **Frameworks**: MERN Stack, Flask
      - **Cloud Technologies**: AWS EC2, S3, Docker
      - **Certifications**:   
        - Front-End Web Dev, HKUST (2021)  
        - Neural Networks & Deep Learning, DeepLearning.ai (2022)
        
  # Projects Section
  - title: Projects
    layout: list
    content:
    
      - layout: top-middle
        border: weak
        title:  SurfStore- DropBox Based Clone
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/fault-tolerant-NFS.git
        description: |
          - Developed a scalable and fault-tolerant networked file storage application in Go, allowing users to seamlessly sync files to and from the cloud.
          - Designed a distributed system architecture using consistent hashing to ensure efficient data distribution and scalability.
          - Implemented the RAFT consensus algorithm to achieve fault tolerance.
          - Tools: Go, ProtoBuf

      - layout: top-middle
        border: weak
        title: Scaling Electro-Cardiac Simulation Algorithm Using MPI
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/MPI-Parallelized-Aliev-Panfilov-Simulation.git
        description: |
          - Used MPI to enhance the scalability of cardiac simulation algorithm for biomedical research.
          - Optimized communication and exploited spatial locality techniques to reduce delays.
          - Conducted strong and weak scaling studies, achieving efficiency greater than 1.0 and a peak performance of 1.96 Tflops/s with 384 cores.
          - Tools: OpenMPI, C++


      - layout: top-middle
        border: weak
        title: Optimized Matrix Calculations Using GPU Acceleration (CUDA)
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/Matrix-Multiplication-on-GPU-with-CUDA.git
        description: |
          - Optimized square matrix operations on a single NVIDIA T104 GPU, achieving 3.6 TFlops/s on 4096-sized matrices.
          - Improved performance by leveraging shared memory, advanced GPU architecture and increased instruction-level parallelism.
          - Tools: CUDA, C

      - layout: top-middle
        border: weak
        title: Network Intrusion Detection System using Autoencoders
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/Network-Intrusion-Detection-System-using-Autoencoders
        description: |
          - Developed an anomaly detection model using an autoencoder architecture trained on the CIC-IDS-2017 dataset, achieving 86% accuracy.
          - Integrated the model with CICFlowMeter using Redis and Elastic Stack to enable real-time network traffic monitoring.
          - Tools: PyTorch, Redis

      - layout: top-middle
        border: weak
        title: Library Management System
        description: |
          - Developed a user-friendly front-end interface with Java Swing, enhancing usability and navigation.
          - Designed optimized MySQL schema using normalization for data integrity, minimizing redundancy.
          - Implemented the designed schema, improving system performance by enhancing data storage and retrieval efficiency.
          - Utilized Java multithreading for concurrent operations, enhancing system responsiveness
          - Tools: Java, MySQL
          
      - layout: top-middle
        border: weak
        title: Interactive Demo App for Learning Extractive Text Summarization
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/SMA_Vlab
        description: |
          - Designed a Streamlit-based application for interactive learning of extractive text summarization in an NLP course.
          - Implemented cosine similarity to provide visual simulations, enhancing students' understanding.

      - layout: top-middle
        border: weak
        title: Plant Leaf Disease Detection using Ensemble Learning
        description: |
          - Built a Flask-based app to help farmers identify plant diseases in real time using uploaded leaf images.
          - Leveraged image preprocessing and ensemble learning, combining three convolutional neural networks for improved performance.
          - Dataset: PlantVillage | Tools: Flask, TensorFlow

      - layout: top-middle
        border: weak
        title: Search Engine for Vedas
        description: |
          - Created a Flask-based search engine using Elasticsearch and fscrawler for phrase-based searches in Vedic literature.
          - Participated in the Smart India Hackathon 2022, optimizing information retrieval with database indexing.

  # Experience Section
  - title: Experience
    layout: list
    content:
      - layout: left
        title: CoE-CNDS Laboratory - VJTI, Mumbai, India
        sub_title: Development Intern
        caption: December 2020 - April 2021
        description: |
          - Developed a dashboard for visualizing honeypot server logs in real time, aiding research in cyber-physical systems security.
          - Enhanced the lab's honeypot data collection, increasing log granularity for detailed analysis.
          - Skills: Web Development, Python, JavaScript, Redis, Wireshark

      - layout: left
        title: WIFIRE Lab, San Diego Supercomputer Center
        sub_title: Graduate Student Researcher
        caption: April 2024 - Present
        description: |
          -  Conducted research on a 234GB dataset with 1155 samples, each 600 seconds long, to predict future fire spread sequences based on fuel density and environmental conditions.
          -  Utilized a ConvLSTM model in TensorFlow and a Physics Guided loss function to achieve a significant 66.67% improvement in MSE, reducing it from 0.0126 to 0.0042.
 
  

# Footer Settings
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
