# Portfolio Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content Configuration Version
version: 2

# Personal Info
name: Yudhir Hiren Gala
title: Software Engineer
email: ygala@ucsd.edu
website: www.github.com/yg2334/

# Theme Settings
darkmode: false

# Social Links
github_username: yg2334
linkedin_username: yudhir-gala

# Profile Section
about_profile_image: images/pg3.jpg
about_content: | 
  Hi, I’m Yudhir, a Master’s student in Computer Science at the University of California, San Diego. As an aspiring software engineer, I have developed robust applications and web solutions during internships, gaining teamwork and leadership experience along the way. 

  My core interests are in backend development and machine learning, and I am currently exploring microservice architecture and scalable ML system design.

  Key Skills: <mark>MERN</mark>, <mark>Backend Development</mark>, and <mark>Pizza Enthusiast</mark>

content:
  # Projects Section
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Network Intrusion Detection System using Autoencoders
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/Network-Intrusion-Detection-System-using-Autoencoders
        description: |
          - Developed an anomaly detection model using an autoencoder architecture trained on the CIC-IDS-2017 dataset, achieving 86% accuracy.
          - Integrated the model with CICFlowMeter using Redis and Elastic Stack to enable real-time network traffic monitoring.

      - layout: top-middle
        border: weak
        title: Interactive Demo App for Learning Extractive Text Summarization
        additional_links:
          - icon: fab fa-github
            url: https://github.com/yg2334/SMA_Vlab
        description: |
          - Designed a Streamlit-based application for interactive learning of extractive text summarization in an NLP course.
          - Implemented cosine similarity to provide visual simulations, enhancing students' understanding.

      - layout: top-middle
        border: weak
        title: Plant Leaf Disease Detection using Ensemble Learning
        description: |
          - Built a Flask-based app to help farmers identify plant diseases in real time using uploaded leaf images.
          - Leveraged image preprocessing and ensemble learning, combining three convolutional neural networks for improved performance.
          - Dataset: PlantVillage | Tools: Flask, TensorFlow

      - layout: top-middle
        border: weak
        title: Library Management System
        description: |
          - Developed a Java-based system for a course project that simplifies library resource management, check-ins, and book borrowing.
          - Applied object-oriented programming, relational database management, and algorithmic principles.

      - layout: top-middle
        border: weak
        title: Search Engine for Vedas
        description: |
          - Created a Flask-based search engine using Elasticsearch and fscrawler for phrase-based searches in Vedic literature.
          - Participated in the Smart India Hackathon 2022, optimizing information retrieval with database indexing.

  # Experience Section
  - title: Experience
    layout: list
    content:
      - layout: left
        title: CoE-CNDS Laboratory - VJTI, Mumbai, India
        sub_title: Development Intern
        caption: December 2020 - April 2021
        description: |
          - Developed a dashboard for visualizing honeypot server logs in real time, aiding research in cyber-physical systems security.
          - Enhanced the lab's honeypot data collection, increasing log granularity for detailed analysis.
          - Skills: Web Development, Python, JavaScript, Redis, Wireshark

  # Education Section
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of California, San Diego
        sub_title: Master of Science in Computer Science
        caption: 2023 - 2025
        description: |
          - Selected Coursework:
            - Fall 2023: Computer Vision, Recommender Systems, Probabilistic Reasoning
            - Winter 2024: Design and Analysis of Algorithms, Data Systems for ML, Unsupervised Learning

      - layout: left
        title: University of Mumbai
        sub_title: Bachelor of Technology in Computer Engineering
        caption: 2019 - 2023
        description: |
          - Relevant Coursework: Algorithms, OS, DBMS, Networks, Cryptography, Big Data Analytics, Machine Learning

  # Technical Skills
  - title: Technical Skills
    layout: text
    content: |
      - **Languages**: C, C++, Python, JavaScript, Java  
      - **Tools**: GitHub, ELK Stack, d3.js, Pandas, PyTorch, React.js, Docker  
      - **Databases**: MySQL, MongoDB, Elasticsearch  
      - **Frameworks**: MERN Stack, Flask, Tornado  
      - **Certifications**: 
        - Front-End Web Dev, HKUST (2021)  
        - Neural Networks & Deep Learning, DeepLearning.ai (2022)

# Footer Settings
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
